name: flowstate
description: "Fitness Tracker App built using Flutter, designed to help users maintain a healthy lifestyle by logging workouts, tracking calorie intake, and visualizing progress over time"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  intl: ^0.19.0
  fl_chart: ^0.66.2
  sqflite: ^2.3.3
  path_provider: ^2.1.3
  flutter_local_notifications: ^17.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true